services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /app/env
    environment:
      - DEBUG=True
      - DATABASE_URL=mysql://root:root@db:3306/smartcity_db
      - AI_MODEL_URL=http://ai-model:5000
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend

  ai-model:
    build: ./backend/model_IA
    ports:
      - "5000:5000"
    volumes:
      - ./backend/model_IA:/app
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=True
    restart: unless-stopped

  db:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=smartcity_db
      - MYSQL_USER=smartenviro
      - MYSQL_PASSWORD=smartenviro
    command: --default-authentication-plugin=mysql_native_password --innodb-use-native-aio=0
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data: