services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /app/env
    environment:
      - DEBUG=True
      - DATABASE_URL=mysql://root:root@db:3306/smartcity_db
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend

  db:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/Script.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=smartcity_db
      - MYSQL_USER=smartenviro
      - MYSQL_PASSWORD=smartenviro
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"

volumes:
  mysql_data: