[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/health/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[[services]]
name = "backend"
source = "backend"

[services.variables]
DEBUG = "False"
PYTHONUNBUFFERED = "1"
RAILWAY_ENVIRONMENT = "production"
ALLOWED_HOSTS = ".railway.app,localhost,127.0.0.1"
CORS_ALLOW_ALL_ORIGINS = "False"
SECURE_SSL_REDIRECT = "True"

[[services]]
name = "frontend"
source = "frontend"

[services.variables]
NODE_ENV = "production"