[build]
builder = "nixpacks"

[deploy]
startCommand = "python manage.py migrate && python manage.py runserver 0.0.0.0:$PORT"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[variables]
DEBUG = "False"
PYTHONUNBUFFERED = "1"
RAILWAY_ENVIRONMENT = "production"
ALLOWED_HOSTS = ".railway.app,localhost,127.0.0.1"
CORS_ALLOW_ALL_ORIGINS = "False"
SECURE_SSL_REDIRECT = "False"