# Generated by Django 5.1.7 on 2025-07-08 12:00

from django.db import migrations


def create_default_roles(apps, schema_editor):
    """Create default roles: admin and citizen"""
    Role = apps.get_model('users', 'Role')
    
    # Create admin role
    Role.objects.get_or_create(
        name='admin',
        defaults={'description': 'Administrateur avec accès complet au système'}
    )
    
    # Create citizen role
    Role.objects.get_or_create(
        name='citizen',
        defaults={'description': 'Citoyen avec accès aux fonctionnalités de base'}
    )


def reverse_default_roles(apps, schema_editor):
    """Remove default roles"""
    Role = apps.get_model('users', 'Role')
    Role.objects.filter(name__in=['admin', 'citizen']).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_roles, reverse_default_roles),
    ]